from colorama import Fore
import datetime
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives import serialization
from cryptography.x509.oid import NameOID
from cryptography import x509

class CertificateAuthority:
    def __init__(self):
        self.root_key = None
        self.subject = None
        self.root_cert = None

    def generate_ca_keys(self):
        try:
            self.root_key = ec.generate_private_key(ec.SECP256R1())
            self.subject = issuer = x509.Name([
                x509.NameAttribute(NameOID.COUNTRY_NAME, "UK"),
                x509.NameAttribute(NameOID.ORGANIZATION_NAME, "My Company"),
                x509.NameAttribute(NameOID.COMMON_NAME, "PyCA Docs Root CA"),
            ])
            print(Fore.GREEN + 'Success: CA keys Generated!')
            return self.root_key and self.subject 
        except Exception as e:
            print(Fore.RED + f'Error: Failed to Generate CA Keys! {e}')
            return None

    def load_csr(self):
        try:
            with open('csr.pem', 'rb') as f:
                csr = x509.load_pem_x509_csr(f.read())
            print(Fore.GREEN + 'Success: CSR File Loaded!')
            return csr
        except Exception as e:
            print(Fore.RED + f'Error: CSR File Not Found! {e}')
            return None

    # Our certificate will be valid for ~10 years
    def create_root_certificate(self):
        if self.root_key is None or self.subject is None:
            print(Fore.RED + f'Error: CA Keys Generation Failed!')
            return None
        try:
            self.root_cert = x509.CertificateBuilder().subject_name(
                self.subject
            ).issuer_name(
                self.subject
            ).public_key(
                self.root_key.public_key()
            ).serial_number(
                x509.random_serial_number()
            ).not_valid_before(
                datetime.datetime.now(datetime.timezone.utc)
            ).not_valid_after(
                datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=365*10)
            ).add_extension(
                x509.BasicConstraints(ca=True, path_length=None),
                critical=True,
            ).add_extension(
                x509.KeyUsage(
                    digital_signature=True,
                    content_commitment=False,
                    key_encipherment=False,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=True,
                    crl_sign=True,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            ).add_extension(
                x509.SubjectKeyIdentifier.from_public_key(self.root_key.public_key()),
                critical=False,
            ).sign(self.root_key, hashes.SHA256())
            print(Fore.GREEN + 'Success: Root Certificate Created!')
            return self.root_cert
        except Exception as e:
            print(Fore.RED + f'Error: Root Certificate Failed!')
            return None

    def sign_csr(self, csr):
        if self.root_key is None or self.root_cert is None:
            print(Fore.RED + f'Error: CA Not Initialized!')
            return None
        try:
            builder = x509.CertificateBuilder().subject_name(
                csr.subject
            ).issuer_name(
                self.root_cert.subject
            ).public_key(
                csr.public_key()
            ).serial_number(
                x509.random_serial_number()
            ).not_valid_before(
                datetime.datetime.now(datetime.timezone.utc)
            ).not_valid_after(
                datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=365*10)
            )

            for extension in csr.extensions:
                builder = builder.add_extension(extension.value, critical=extension.critical)
            self.cert = builder.sign(self.root_key, hashes.SHA256())
            print(Fore.GREEN + 'Success: Certificate Issued!!')
            return self.cert
        except Exception as e:
            print(Fore.RED + f'Error: Certificate Failed!')
            return None

    def save_certificate(self, cert):
        try:
            with open('certificate.pem', 'wb') as f:
                print(Fore.GREEN + 'Success: Certificate Generated by CA!')
                f.write(cert.public_bytes(serialization.Encoding.PEM))
        except Exception as e:
            print(Fore.RED + 'Error: Certificate Failed to Generate by CA!')
            return None

    def Revoke_Certificate(self, cert_serial_number):
        if self.root_key is None or self.root_cert is None:
            print(Fore.RED + f'Error: CA Not Initialized!')
            return None
        try:
            one_day = datetime.timedelta(1, 0, 0)
            revoked_cert = x509.RevokedCertificateBuilder().serial_number(
                cert_serial_number
            ).revocation_date(
                datetime.datetime.now(datetime.timezone.utc)
            ).build()
         
            builder = x509.CertificateRevocationListBuilder()
            builder = builder.issuer_name(self.root_cert.subject)
            builder = builder.last_update(datetime.datetime.now(datetime.timezone.utc))
            builder = builder.next_update(datetime.datetime.now(datetime.timezone.utc) + one_day)
            builder = builder.add_revoked_certificate(revoked_cert)

            crl = builder.sign(
                private_key=self.root_key, 
                algorithm=hashes.SHA256(),
            )
            print(Fore.GREEN + 'Success: CA Revoked Certificate!')
        except Exception as e:
            print(Fore.RED + f'Error: CA Failed to Revoke Certificate!')
            return None
